version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: eigen
      POSTGRES_PASSWORD: EigenTest
      POSTGRES_DB: eigen-db
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - eigen_network
  api:
    image: eigen-test:prod
    build:
      context: .
      dockerfile: dockerfiles/dev.dockerfile
    container_name: api_container
    environment:
      - DATABASE_URL=postgresql://eigen:EigenTest@postgres/eigen-db
    networks:
      - eigen_network
    ports:
      - '5000:5000'
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  eigen_network:
    driver: bridge
